version: '3.7'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_URI=${POSTGRES_URI}
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local


networks:
  networks_bridge:
    external:
      name: networks_bridge

